title: UltraEP Blog
description: UltraEP blog in Chinese and English.
lang: en
github_url: "https://github.com/Dots-Infra/UltraEP"
markdown: kramdown
permalink: pretty

baseurl: "/UltraEP"
url: "https://Dots-Infra.github.io"

exclude:
  - .bundle
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
